-- DROP IF EXIST DATABASE
DROP DATABASE IF EXISTS Practica3;

-- CREATE DATABASE
CREATE DATABASE Practica3;

-- USE DATABASE
USE Practica3;

-- CREATE TABLE TYPE OF USER
CREATE TABLE TipoUsuario(
	idTipoUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	descripcion VARCHAR(100) NOT NULL
);

-- CREATE TABLE USER
CREATE TABLE Usuario(
	idUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(255) NOT NULL,
	nombre VARCHAR(100) NULL,
	apellido VARCHAR(100) NULL,
	conexion DATETIME NULL,
    idTipoUsuario INT NOT NULL,
	FOREIGN KEY (idTipoUsuario) REFERENCES TipoUsuario(idTipoUsuario)
	ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- CREATE TABLE MESSAGES
DROP TABLE IF EXISTS Mensaje;
CREATE TABLE Mensaje(
    idMensaje INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUsuario1 INT NOT NULL,
    idUsuario2 INT NOT NULL,
    cuerpo VARCHAR(255) NOT NULL,
    fecha DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    fechaLeido DATETIME NULL,
    leido TINYINT NULL DEFAULT 0,
    estado TINYINT NULL DEFAULT 0,
    FOREIGN KEY (idUsuario1) REFERENCES Usuario(idUsuario)
	ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (idUsuario2) REFERENCES Usuario(idUsuario)
	ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- CREATE TABLE MESSAGES
DROP TABLE IF EXISTS DetalleMensaje;
CREATE TABLE DetalleMensaje(
    idDetalleMensaje INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idMensaje INT NOT NULL,
    cuerpo VARCHAR(255) NOT NULL,
    FOREIGN KEY (idMensaje) REFERENCES Mensaje(idMensaje)
	ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- SP CREAR MENSAJE
DELIMITER $$
CREATE PROCEDURE SP_CreateMensaje
(IN _idUsuario1 INT, _idUsuario2 INT, _cuerpo VARCHAR(255))
BEGIN
	INSERT INTO Mensaje(idUsuario1, idUsuario2, cuerpo) VALUES(_idUsuario1, _idUsuario2, _cuerpo);
END;
$$